### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by ricochet** [diekmann/wasm-fizzbuzz#11]
The tutorials are great! Thank you for putting this together.

I would like to build on the doom example for my own, "But can it run DOOM" project. Does this project have a LICENSE?

@diekmann

**Comment by diekmann** [comment]
Hi Bailey,

thanks for your interest. I'm generally a fan of free open-source licenses. Yet, this personal hobby project already contains a lot of third party licensed code. For example,

* the [DOOM license](https://github.com/diekmann/wasm-fizzbuzz/blob/main/doom/linuxdoom-1.10/DOOMLIC.TXT)
* the [DOOM shareware demo gamefile](https://github.com/diekmann/wasm-fizzbuzz/blob/main/doom/linuxdoom-1.10/doom1.wad) which I got from https://archive.org/details/2020_03_22_DOOM
* the [musl license](https://github.com/diekmann/wasm-fizzbuzz/blob/main/doom/musl-1.2.2/COPYRIGHT)
* the musl [`arch`](https://github.com/diekmann/wasm-fizzbuzz/tree/main/doom/musl-1.2.2/arch/wasm32) directory, which [I got from emscripten](https://github.com/emscripten-core/emscripten/tree/efede793113ce1aa4d38d4f2df08e6b251cc53c6/system/lib/libc/musl/arch/emscripten) where I don't know if the musl license or the emscripten license applies
* the [clang runtime](https://github.com/diekmann/wasm-fizzbuzz/tree/main/doom/clang_compiler_rt) which I got from https://github.com/llvm/llvm-project/
* The dual licensed [lazy_static crate](https://github.com/diekmann/wasm-fizzbuzz/blob/51a7030bea563d96027301a36619c17347b9270d/doom/Cargo.toml#L10)
* ...

I'm not a lawyer and I have no idea how to combine this under one unified standard FOSS license, if at all possible.

I'm happy to declare that my writing and code could be CC BY NC (NC because this is my understanding of DooM's license).

I like that everything needed to compile the code is just in this self-contained repository and that the GitHub pages can directly show the demo. My guess is, to make this tutorial licensable (is that even the correct term?) I need to remove lots of the third party stuff, for example, the `doom1.wad`. So for the sake of having this self-contained tutorial with the great GitHub pages, I chose not to add a LICENSE.

**Comment by ricochet** [comment]
Thank you! I was similarly muddled by the mix of licenses that I couldn't quite make heads or tails of what to add for my own project.
